// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_tutorial/test/features/counter/domain/usecases/counter_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_tutorial/features/counter/domain/entities/counter_entity.dart'
    as _i2;
import 'package:flutter_tutorial/features/counter/domain/repositories/counter_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCounterEntity_0 extends _i1.SmartFake implements _i2.CounterEntity {
  _FakeCounterEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CounterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCounterRepository extends _i1.Mock implements _i3.CounterRepository {
  MockCounterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CounterEntity> getCounter() => (super.noSuchMethod(
        Invocation.method(
          #getCounter,
          [],
        ),
        returnValue: _i4.Future<_i2.CounterEntity>.value(_FakeCounterEntity_0(
          this,
          Invocation.method(
            #getCounter,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CounterEntity>);

  @override
  _i4.Future<_i2.CounterEntity> incrementCounter() => (super.noSuchMethod(
        Invocation.method(
          #incrementCounter,
          [],
        ),
        returnValue: _i4.Future<_i2.CounterEntity>.value(_FakeCounterEntity_0(
          this,
          Invocation.method(
            #incrementCounter,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CounterEntity>);

  @override
  _i4.Future<_i2.CounterEntity> decrementCounter() => (super.noSuchMethod(
        Invocation.method(
          #decrementCounter,
          [],
        ),
        returnValue: _i4.Future<_i2.CounterEntity>.value(_FakeCounterEntity_0(
          this,
          Invocation.method(
            #decrementCounter,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CounterEntity>);

  @override
  _i4.Future<void> resetCounter() => (super.noSuchMethod(
        Invocation.method(
          #resetCounter,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
