// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_tutorial/test/features/counter/presentation/providers/counter_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_tutorial/features/counter/domain/entities/counter_entity.dart'
    as _i3;
import 'package:flutter_tutorial/features/counter/domain/repositories/counter_repository.dart'
    as _i2;
import 'package:flutter_tutorial/features/counter/domain/usecases/decrement_counter_usecase.dart'
    as _i7;
import 'package:flutter_tutorial/features/counter/domain/usecases/get_counter_usecase.dart'
    as _i4;
import 'package:flutter_tutorial/features/counter/domain/usecases/increment_counter_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCounterRepository_0 extends _i1.SmartFake
    implements _i2.CounterRepository {
  _FakeCounterRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCounterEntity_1 extends _i1.SmartFake implements _i3.CounterEntity {
  _FakeCounterEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCounterUseCase extends _i1.Mock implements _i4.GetCounterUseCase {
  MockGetCounterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CounterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCounterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CounterRepository);

  @override
  _i5.Future<_i3.CounterEntity> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.CounterEntity>.value(_FakeCounterEntity_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.CounterEntity>);
}

/// A class which mocks [IncrementCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementCounterUseCase extends _i1.Mock
    implements _i6.IncrementCounterUseCase {
  MockIncrementCounterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CounterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCounterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CounterRepository);

  @override
  _i5.Future<_i3.CounterEntity> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.CounterEntity>.value(_FakeCounterEntity_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.CounterEntity>);
}

/// A class which mocks [DecrementCounterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecrementCounterUseCase extends _i1.Mock
    implements _i7.DecrementCounterUseCase {
  MockDecrementCounterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CounterRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCounterRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CounterRepository);

  @override
  _i5.Future<_i3.CounterEntity> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.CounterEntity>.value(_FakeCounterEntity_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.CounterEntity>);
}
